import { RouteTree } from "../router/index";
import * as Route0 from "./routes/_index";
import * as Route1 from "./routes/index";
import * as Route2 from "./routes/server.$serv";
import * as Route3 from "./routes/server.$serv.$user";
import * as Route4 from "./routes/server.$serv.$user.history";
import * as Route5 from "./routes/server.$serv._index";
import * as Route6 from "./routes/server.$serv.accounts";
import * as Route7 from "./routes/server._index";
import * as RootRoute from "./root";

export const Router = new RouteTree;
Router.ingest("_index", Route0, []);
Router.ingest("index", Route1, []);
Router.ingest("server.$serv", Route2, []);
Router.ingest("server.$serv.$user", Route3, []);
Router.ingest("server.$serv.$user.history", Route4, []);
Router.ingest("server.$serv._index", Route5, []);
Router.ingest("server.$serv.accounts", Route6, []);
Router.ingest("server._index", Route7, []);
Router.assignRoot(RootRoute);
