name: Deploy to PI

on:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}

          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh

            PATH="/home/me/.nvm/versions/node/v19.9.0/bin:$PATH"

            cd /srv/predictable/
            npm run upgrade